import './globals.css'
import { Inter } from 'next/font/google'
import { ReactQueryClientProvider } from '@/components/ReactQueryClientProvider';
import ThemeClient from '@/components/ThemeClient';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ReactQueryClientProvider>
      <ThemeClient>
        <html lang="en">
          <body className={inter.className}>
            {children}
          </body>
        </html>
      </ThemeClient>
    </ReactQueryClientProvider>
  )
}
